keys:
  - &admin age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy
  - &member1 age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy
  - &member2 age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy

creation_rules:
  - path_regex: ^secrets.yaml$
    key_groups:
      - age:
          - *admin
          - *member1
          - *member2
